# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160928_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/%Y/%m/'),
        ),
    ]
